create table if not exists public.calculations (
  id bigint generated by default as identity primary key,
  user_email text not null,
  user_name text,
  spam_daily numeric not null default 0,
  email_monthly numeric not null default 0,
  cloud_gb numeric not null default 0,
  media_gb numeric not null default 0,
  app_cleanup_gb numeric not null default 0,
  total_co2_saved numeric not null default 0,
  tree_equivalent numeric not null default 0,
  digital_cleanup_score integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.calculations
  add column if not exists user_email text,
  add column if not exists user_name text,
  add column if not exists spam_daily numeric not null default 0,
  add column if not exists email_monthly numeric not null default 0,
  add column if not exists cloud_gb numeric not null default 0,
  add column if not exists media_gb numeric not null default 0,
  add column if not exists app_cleanup_gb numeric not null default 0,
  add column if not exists total_co2_saved numeric not null default 0,
  add column if not exists tree_equivalent numeric not null default 0,
  add column if not exists digital_cleanup_score integer not null default 0,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'calculations' and column_name = 'email'
  ) then
    execute 'update public.calculations set user_email = coalesce(user_email, email) where user_email is null';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'calculations' and column_name = 'daily_spam'
  ) then
    execute 'update public.calculations set spam_daily = coalesce(spam_daily, daily_spam, 0)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'calculations' and column_name = 'cloud_deleted_gb'
  ) then
    execute 'update public.calculations set cloud_gb = coalesce(cloud_gb, cloud_deleted_gb, 0)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'calculations' and column_name = 'total_saving_kg'
  ) then
    execute 'update public.calculations set total_co2_saved = coalesce(total_co2_saved, total_saving_kg, 0), tree_equivalent = coalesce(tree_equivalent, total_saving_kg / 20, 0)';
  end if;
end $$;

create index if not exists calculations_user_email_created_at_idx
  on public.calculations (user_email, created_at desc);

alter table public.calculations enable row level security;

drop policy if exists "Allow anon calculation reads" on public.calculations;
drop policy if exists "Allow anon calculation inserts" on public.calculations;

create policy "Allow anon calculation reads"
  on public.calculations
  for select
  to anon
  using (true);

create policy "Allow anon calculation inserts"
  on public.calculations
  for insert
  to anon
  with check (true);
